### ISSUE TITLE
PersonNameComponents and email are all null in AppleIdCredential when running on a live device

### ISSUE THREAD

**Issue by therealjohnsummer** [tomgilder/flutter_sign_in_with_apple#15]
When using Face ID login or ANY Authentication mechanism for an iPhone  - **AuthorizationResult** contains ALL null fields. This includes CREDENTIAL.

When we test on a simulator - we get values for CREDENTIAL, i.e email, fullname, familyName, givenName... 

Tested on live iPhone X and iPhone 11 Pro MAX device.

**Comment by minhtruong315** [comment]
same error

**Comment by vinwonghk** [comment]
this is an expected behavior, after first time sign in, Apple will not pass user's name and email again.

please check here:
https://stackoverflow.com/questions/57714339/sign-in-with-apple-different-behaviour-simulator-vs-iphone
https://stackoverflow.com/questions/57545635/cannot-get-name-email-with-sign-in-with-apple-on-real-device

**Comment by tomgilder** [comment]
Closing - this is the expected behaviour, see https://forums.developer.apple.com/thread/121496
